{% set name = "pdoc3" %}
{% set version = "0.11.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ea5e84b87a754d191fb64bf5e517ca6c50d0d84a614c1efecf6b46d290ae387

build:
  number: 0
  skip: true  # [py<39]
  entry_points:
    - pdoc = pdoc.cli:main
    - pdoc3 = pdoc.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  host:
    - mako
    - markdown >=3.0
    - pip
    - python >=3.5
    - setuptools_scm
    - setuptools-git
  run:
    - mako
    - markdown >=3.0
    - python

test:
  imports:
    - pdoc
    - pdoc.cli
    - pdoc.html_helpers
  source_files:
    - pdoc/test
    - pdoc/test/__init__.py
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - PYTHONPATH=$SRC_DIR python -m unittest discover -s pdoc.test

about:
  home: https://pdoc3.github.io/pdoc
  license: GNU Affero General Public License v3 or later (AGPLv3+) (AGPL-3.0)
  license_family: AGPL
  summary: Auto-generate API documentation for Python projects.
  description: |
    pdoc3 is a lightweight and fast documentation generator for Python modules.
    It produces clean, customizable HTML documentation directly from the source code
    and its docstrings, supporting both public and private APIs. pdoc3 is ideal
    for projects that value simplicity and want to keep documentation closely tied
    to the codebase.
  dev_url: https://github.com/pdoc3/pdoc
  doc_url: https://pdoc3.github.io/pdoc/doc/pdoc

extra:
  recipe-maintainers:
    - msarahan
