{% set name = "pdoc3" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1848d5485b8dd4662272f83bb5f7df4a68e0a5d76c87be30327977777168894

build:
  number: 0
  noarch: python
  entry_points:
    - pdoc = pdoc.cli:main
    - pdoc3 = pdoc.cli:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - mako
    - markdown >=3.0
    - pip
    - python >=3.5
    - setuptools_scm
    - setuptools-git
  run:
    - mako
    - markdown >=3.0
    - python >=3.5

test:
  imports:
    - pdoc
    - pdoc.cli
    - pdoc.html_helpers

  commands:
    - pdoc --help
    - pdoc3 --help
    # commenting at rev 0.7.2 because of an irrelevant git test failing.
    #     https://github.com/conda-forge/staged-recipes/pull/10220#issuecomment-557137812
    # - python -m pdoc.test.__init__

about:
  home: https://pdoc3.github.io/pdoc/
  license: GNU Affero General Public v3 or later (AGPLv3+)
  license_family: AGPL
  license_file: LICENSE.txt
  summary: Auto-generate API documentation for Python projects.

extra:
  recipe-maintainers:
    - msarahan
