{% set name = "pdoc3" %}
{% set version = "0.11.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ea5e84b87a754d191fb64bf5e517ca6c50d0d84a614c1efecf6b46d290ae387

build:
  number: 0
  skip: true  # [py<39]
  entry_points:
    - pdoc = pdoc.cli:main
    - pdoc3 = pdoc.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools_scm
    - setuptools-git
  run:
    - mako
    - markdown >=3.0
    - python

test:
  requires:
    - pip
  imports:
    - pdoc
    - pdoc.cli
    - pdoc.html_helpers
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - PYTHONPATH=$SRC_DIR python -m unittest discover -s pdoc.test  # [not win]
    - set PYTHONPATH=%SRC_DIR% && python -m unittest discover -s pdoc.test -v  # [win]

about:
  home: https://pdoc3.github.io/pdoc
  dev_url: https://github.com/pdoc3/pdoc
  doc_url: https://pdoc3.github.io/pdoc/doc/pdoc
  license: AGPL-3.0-only
  license_family: AGPL
  license_file: LICENSE.txt
  summary: Auto-generate API documentation for Python projects.
  description: |
    Python package pdoc provides types, functions, and a command-line interface 
    for accessing public documentation of Python modules, and for presenting it 
    in a user-friendly, industry-standard open format. It is best suited for 
    small- to medium-sized projects with tidy, hierarchical APIs.

extra:
  recipe-maintainers:
    - msarahan
